version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      runtime-dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
