version: "2"

# Linting config for whatsapp-bridge
# staticcheck disabled due to deprecated whatsmeow imports (requires library update)

linters:
  enable:
    - govet
    - errcheck
    - unused
    - ineffassign
  disable:
    - staticcheck   # Deprecated whatsmeow imports (need library update)

run:
  timeout: 5m
