# Relaxed linting config for initial fork
# TODO: Enable stricter linting and fix issues over time

linters:
  enable:
    - govet
  disable:
    - errcheck      # Many unchecked json.Encode returns
    - staticcheck   # Deprecated whatsmeow imports (need library update)
    - unused        # Some unused functions exist
    - ineffassign   # Some ineffectual assignments exist

run:
  timeout: 5m
