name: Dependabot auto-merge

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  auto-merge:
    uses: verygoodplugins/.github/.github/workflows/dependabot-auto-merge.yml@main
    secrets: inherit
